### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by TSSHenrik** [Lenni0451/EventAPI#1]
Do u have discord? I want to ask u something.

**Comment by Lenni0451** [comment]
No, I don't have Discord.

**Comment by TSSHenrik** [comment]
OK. So, this is a bit off topic. Do u still have the source code of the AntiV client?
It was so perfect and you could easily just delete the login form out of it.

**Comment by Lenni0451** [comment]
I normally would not anwer that but lets just say AntiV is dead. The server is still running but you can not register an account anymore. The ones with a account can still use it but you should not because I could turn off the server at any time. I don't know how long I will let the server on but yeah.
